src/rtchat/apps/account/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),
    path("logout", views.logout, name="logout"),
    path("signup", views.SignupView.as_view(), name="signup"),
]

src/rtchat/apps/chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
]

src/rtchat/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(
        "account/",
        include(("rtchat.apps.account.urls", "account"), namespace="account"),
    ),
    path("chat/", include(("rtchat.apps.chat.urls", "chat"), namespace="chat")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/rtchat/apps/chat/models.py
from django.contrib.auth.models import User
from django.db import models


class Room(models.Model):
    name = models.CharField(max_length=32)

    @property
    def group_name(self) -> str:
        return f"chat_room_{self.name}"


class Message(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    sender = models.ForeignKey(User, on_delete=models.PROTECT)
    text = models.CharField(max_length=128)
    timestamp = models.DateTimeField(auto_now_add=True)

src/rtchat/apps/account/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            "username",
            "password1",
            "password2",
            "first_name",
            "last_name",
            "email",
        ]

src/rtchat/apps/account/views.py
from django.contrib import auth
from django.contrib.auth import views as auth_views
from django.contrib.auth.models import User
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect
from django.views.generic import CreateView

from rtchat.apps.account.forms import SignupForm


def logout(request: HttpRequest) -> HttpResponse:
    auth.logout(request)
    return redirect("account:login")


class LoginView(auth_views.LoginView):
    template_name = "account/login.html"


class SignupView(CreateView):
    model = User
    form_class = SignupForm
    template_name = "account/signup.html"

    def form_valid(self, form):
        """
        Override successful form submission to log the user in and redirect them.
        """
        self.object = form.save()
        auth.login(self.request, user=self.object)
        return redirect("chat:index")

src/rtchat/apps/chat/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

from rtchat.apps.chat.models import Room


def index(request: HttpRequest) -> HttpResponse:
    return render(request, "chat/index.html")


@login_required
def room(request: HttpRequest, room_name: str) -> HttpResponse:
    room, _created = Room.objects.get_or_create(name=room_name)
    messages = room.message_set.order_by("timestamp").all()
    return render(
        request,
        "chat/room.html",
        {"room_name": room_name, "messages": messages},
    )

src/rtchat/apps/chat/templates/chat/index.html
{% extends "layout.html" %}

{% block title %}Chat Rooms{% endblock %}

{% block topbar_title %}Chat{% endblock %}

{% block content %}
  What chat room would you like to enter?<br>
  <input id="room-name-input" type="text" size="100">
  <input id="room-name-submit" type="button" value="Enter">

  <script>
    document.querySelector("#room-name-input").focus();
    document.querySelector("#room-name-input").onkeyup = function(e) {
      if (e.key === "Enter") {
        document.querySelector("#room-name-submit").click();
      }
    };

    document.querySelector("#room-name-submit").onclick = function(e) {
      var roomName = document.querySelector("#room-name-input").value;
      window.location.pathname = "/chat/" + roomName + "/";
    };
  </script>
{% endblock %}

src/rtchat/apps/chat/templates/chat/room.html
{% extends "layout.html" %}

{% block title %}Realtime Chat{% endblock %}

{% block topbar_title %}Chat Room: {{ room_name }}{% endblock %}

{% block content %}
  <div class="messages">
    {% for message in messages %}
      <div class="message">
        <span class="message-sender">{{ message.sender }}:</span>
        <span class="message-text">{{ message.text }}</span>
      </div>
    {% endfor %}
  </div>
  <input id="chat-message-input" type="text" size="100">
  <input id="chat-message-submit" type="button" value="Send">
  {{ room_name|json_script:"room-name" }}
  <script>
    const roomName = JSON.parse(document.getElementById("room-name").textContent);

    const chatSocket = new WebSocket(
      "ws://"
      + window.location.host
      + "/ws/chat/"
      + roomName
      + "/"
    );

    function scrollToBottom() {
      const messages = document.querySelector(".messages");
      messages.scrollTop = messages.scrollHeight;
    }
    scrollToBottom();

    chatSocket.onmessage = function(e) {
      const data = JSON.parse(e.data);
      console.log(data);

      const sender = document.createElement("span");
      sender.className = "message-sender";
      sender.innerText = data.message.sender + ":";

      const text = document.createElement("span");
      text.className = "message-text";
      text.innerText = " " + data.message.text;

      const message = document.createElement("div");
      message.className = "message";
      message.appendChild(sender);
      message.appendChild(text);

      document.querySelector(".messages").appendChild(message);
      scrollToBottom();
    };

    chatSocket.onClose = function(e) {
      console.error("Chat socket closed unexpectedly");
    };

    document.querySelector("#chat-message-input").focus();
    document.querySelector("#chat-message-input").onkeyup = function(e) {
      if (e.key === "Enter") {
        document.querySelector("#chat-message-submit").click();
      }
    };

    document.querySelector("#chat-message-submit").onclick = function(e) {
      const messageInputDom = document.querySelector("#chat-message-input");
      const message = messageInputDom.value;
      chatSocket.send(JSON.stringify({
        "message": message,
      }));
      messageInputDom.value = "";
    };
  </script>
{% endblock %}

src/rtchat/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static "reset.css" %}">
    <link rel="stylesheet" href="{% static "layout.css" %}">
  </head>
  <body>
    <div class="main">
      <div class="topbar">
        <span class="topbar-title">{% block topbar_title %}{% endblock %}</span>
        <span class="topbar-auth">
          {% if user.is_authenticated %}
            {{ user }} | <a href="{% url "account:logout" %}">logout</a>
          {% else %}
            <a href="{% url "account:login" %}">login</a> | <a href="{% url "account:signup" %}">signup</a>
          {% endif %}
        </span>
      </div>
      <div class="content">
        {% block content %}{% endblock %}
      </div>
    </div>
  </body>
</html>